### ISSUE TITLE
no_set_bg removed?

### ISSUE THREAD

**Issue by rcurtin** [cameronleger/goes16-background#7]
I updated from a very old version today and noticed that the --no_set_bg option is no longer available.  Was there a reason for this change?  It would be great to have it back.  (I do some postprocessing on the output after this tool downloads the images for me.)

Thank you for the nice utility!

**Comment by cameronleger** [comment]
Hello! I believe that since the inception of this particular repository, that has not been an available option. It's possible that it was in an older version of something that this was forked from, but I also try to keep this in-line with upstream and I don't believe that's an option there either.

However, it should be easy for you to modify the environment that the script is run in, so that essentially it fails to detect how it should set the background:

https://github.com/cameronleger/goes16-background/blob/836d38db167aae3132a40e862bffe7e9274cbad6/goes16background/utils.py#L88

**Comment by rcurtin** [comment]
So, it turns out I am clueless.  Apparently, several years ago when I set this up, I added a `--no_set_bg` option locally but never contributed it back upstream.  So it never existed in this repository.  Anyway, I opened a PR with the support if you'd like to add it---but please don't feel obligated. :+1:
